runtime: nodejs18
instance_class: F4
automatic_scaling:
  target_cpu_utilization: 0.95
  max_instances: 5
env_variables:
  NODE_ENV: "production"
vpc_access_connector:
  name: projects/endeavor-b285f/locations/europe-west3/connectors/endeavour-vpc-connector
